# Generated by Django 5.2.6 on 2025-11-12 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Historia', 'Historia'), ('Matematicas', 'Matemáticas'), ('Informatica', 'Informática'), ('Medicina', 'Medicina')], max_length=100)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('A distancia', 'A distancia')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_documentacion', models.BooleanField(default=True)),
                ('estado_pago', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mensajes.carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.perfilalumno')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='mensajes.perfilalumno')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='mensajes.perfilalumno')),
            ],
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('General', 'General'), ('Comunicacion', 'Comunicación'), ('Academica', 'Académica')], default='General', max_length=20)),
                ('motivo', models.CharField(blank=True, help_text='Motivo o descripción asociada a esta preferencia', max_length=200, null=True)),
                ('tareas_pendientes', models.BooleanField(default=True)),
                ('calificaciones_publicadas', models.BooleanField(default=True)),
                ('eventos_academicos', models.BooleanField(default=True)),
                ('anuncios_profesor', models.BooleanField(default=True)),
                ('habilitar_agrupadas', models.BooleanField(default=False)),
                ('hora_envio_agrupadas', models.TimeField(blank=True, null=True)),
                ('correo_electronico', models.BooleanField(default=True)),
                ('aplicacion_movil', models.BooleanField(default=True)),
                ('difusion', models.BooleanField(default=True, help_text='Indica si el alumno acepta recibir mensajes o material de difusión')),
                ('prioridad_notificaciones', models.PositiveIntegerField(default=50)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='mensajes.perfilalumno')),
                ('carrera', models.ForeignKey(blank=True, help_text='Carrera asociada a la preferencia (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mensajes.carrera')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100)),
                ('canal', models.CharField(default='Email', max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='mensajes.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado_envio', models.CharField(max_length=50)),
                ('mensaje', models.TextField(default='mensaje por defecto')),
                ('alumnos', models.ManyToManyField(to='mensajes.perfilalumno')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.tiponotificacion')),
            ],
        ),
    ]
