# Generated by Django 5.2.6 on 2025-11-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='aviso_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
