# Generated by Django 5.2.6 on 2025-11-08 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeinterno',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='mensajes.perfilalumno'),
        ),
        migrations.AlterField(
            model_name='mensajeinterno',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='mensajes.perfilalumno'),
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tareas_pendientes', models.BooleanField(default=True)),
                ('calificaciones_publicadas', models.BooleanField(default=True)),
                ('eventos_academicos', models.BooleanField(default=True)),
                ('anuncios_profesor', models.BooleanField(default=True)),
                ('habilitar_agrupadas', models.BooleanField(default=False)),
                ('hora_envio_agrupadas', models.TimeField(blank=True, null=True)),
                ('correo_electronico', models.BooleanField(default=True)),
                ('aplicacion_movil', models.BooleanField(default=True)),
                ('prioridad_notificaciones', models.PositiveIntegerField(default=50)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='mensajes.perfilalumno')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
            },
        ),
    ]
