# Generated by Django 5.2.6 on 2025-11-08 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_alter_mensajeinterno_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencia',
            name='carrera',
            field=models.ForeignKey(blank=True, help_text='Carrera asociada a la preferencia (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mensajes.carrera'),
        ),
        migrations.AddField(
            model_name='preferencia',
            name='difusion',
            field=models.BooleanField(default=True, help_text='Indica si el alumno acepta recibir mensajes o material de difusión'),
        ),
        migrations.AddField(
            model_name='preferencia',
            name='motivo',
            field=models.CharField(blank=True, help_text='Motivo o descripción asociada a esta preferencia', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='preferencia',
            name='tipo',
            field=models.CharField(choices=[('General', 'General'), ('Comunicacion', 'Comunicación'), ('Academica', 'Académica')], default='General', max_length=20),
        ),
    ]
